const SIDEBAR_COLLAPSE = "SIDEBAR_COLLAPSE";
const SIDEBAR_SPREAD = "SIDEBAR_SPREAD";

const AUTH = "AUTH";
const AUTH_NOT = "AUTH_NOT";

const ADD_EBOOK = "ADD_EBOOK";
const EDIT_EBOOK = "EDIT_EBOOK";

export {
  SIDEBAR_COLLAPSE,
  SIDEBAR_SPREAD,
  AUTH,
  AUTH_NOT,
  ADD_EBOOK,
  EDIT_EBOOK
};
